### PR TITLE
Add missing elements

### PR DESCRIPTION
**Pull request by rbottomley**
I have attempted to add almost all of the missing HTML5 elements. I also grouped them by content category (although lots of elements are in multiple categories so it is a bit subjective).

I removed acronym since it has been dropped from HTML5.

Some of the changes I made to the form examples are based on accessibility recommendations (such as fields should not be contained in their labels).

Let me know if you would like me to make any changes.

### CODE REVIEW

**Comment by dbox** [comment]
I will merge this purely for the Zork reference.

**Comment by dbox** [comment]
First off. Thanks!! Great work here.

This is awesome and I'll certainly merge it. I need some time to properly go over everything.

In the meantime, question: should the phrasing content section be displayed like a list, paragraph style, or some combination of both?

image

**Comment by rbottomley** [comment]
I toyed with how best to do the phrasing content. I ended up doing it like that so that I could group similar elements together. I was also concerned that if I did it as a list of each element individually, it would be too long. I'll change it to whatever way you think is best.

While working at UC Riverside, I had an Easter egg in the campus search engine. If you entered "xyzzy", it responded with "nothing happens". Sadly, it is no longer there.

**Comment by dbox** [comment]
What do you think about this?

https://codepen.io/dbox/pen/PBQLVW

**Comment by dbox** [comment]
can we just move `header` and `footer` into sectioning?

**Comment by rbottomley** [comment]
I like what you did. I had considered adding in-page nav but I didn't want to get carried away (too late), plus it took me a lot longer to do what I did than I thought it would.

`header` and `footer` are not themselves sectioning content—they are palpable content. But sectioning content is what defines their scope, so I dunno... maybe include them their but don't call them sectioning.

**Comment by dbox** [comment]
What should we do for `embed`? Show a `.swf` there or something?

**Comment by rbottomley** [comment]
I did `embed` (`<embed src="playbill.pdf" width="320" height="200" type='application/pdf'>`). `object` was the one I skipped because I no longer know what it would be used for. Flash was the last time I used it. I'll see if I can find a real use for it (it may be a dinosaur that we just choose to ignore). I also didn't do the Ruby elements because I neither know nor care about them.

**Comment by dbox** [comment]
yeah, i just played around with it trying to get it to show SOMETHING, but basically I think it's dead. all the `.swfs` gave security warnings 😂

**Comment by rbottomley** [comment]
I can't find anything that will work in `object`. I have a Zmachine Java applet that would allow you to run Zork :-) , but Java plugins do not work on 64-bit browsers. I give up on `object`. Call the time of death.

**Pull request merged**
